spring:
  application:
    name: signaling
  datasource:
    url: jdbc:mysql://localhost:3306/debate_arena
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:8081
    - http://localhost:8080
    - http://127.0.0.1:3000
    - http://127.0.0.1:8081
    - http://127.0.0.1:8080

jwt:
  secret: mySuperSecretKey1234567890thatIsLongEnoughForHS256
  expiration: 86400000
logging:
  level:
    com.arena.signaling: debug
    org.springframework.web.cors: DEBUG  # CORS 로그 활성화
#    org.hibernate.SQL: debug       # 실행되는 SQL 문 출력
#    org.hibernate.type.descriptor.sql.BasicBinder: trace  # 바인딩되는 값 출력
#    org.hibernate.orm.jdbc.bind: trace                    # Hibernate 6.x 이상에서 바인딩 출력
#    org.hibernate.engine.jdbc.batch.internal.BatchingBatch: debug  # 배치 쿼리 로그
#    org.hibernate: info          # 전체 Hibernate 로그 레벨 (기본 INFO)

server:
  port: 8083